import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import { getAllPackages } from "./actions/package";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const packages = await getAllPackages();
  return (
    <html lang="en">
      <body className={cn(inter.className, "relative")}>
        <NavBar packages={JSON.stringify(packages)} />
        <div className="overflow-hidden rounded-[0.5rem] border bg-background shadow">
        {children}
        </div>
        </body>
    </html>
  );
}
